### PR TITLE
implement -n, --months <num>

### PR DESCRIPTION
**Pull request by quite**

### CODE REVIEW

**Comment by b1rger** [comment]
Interesting! Which `cal(1)` implementation comes with `-n`?

**Comment by b1rger** [comment]
> Interesting! Which `cal(1)` implementation comes with `-n`?

ah, maybe I misinterpreted what the `imitating cal(1)` comment refers to

**Comment by quite** [comment]
the one from util-linux it seems https://github.com/util-linux/util-linux/blob/master/misc-utils/cal.c#L1353

**Comment by quite** [comment]
the comment was only the highlight specifically that we interpret "0" as 1, as that `cal` did...

**Comment by quite** [comment]
But let's not re-implement that quirky accepting of "--months=0"

**Comment by quite** [comment]
Made some small adjustments

**Comment by b1rger** [comment]
Thanks! LGTM and I plan to merge this

**Pull request merged**
